/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { MockEmitter, MockEmitterInterface } from "../MockEmitter";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "Emitted",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "emitSample",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061027d806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063ad602e7814610030575b600080fd5b61004a60048036038101906100459190610148565b61004c565b005b3373ffffffffffffffffffffffffffffffffffffffff167fb79ab70acc7b1f8e8cdeb65fae4e1efd6408c39fd95909059ddd807a9f0d82db84848460405161009693929190610215565b60405180910390a2505050565b600080fd5b600080fd5b6000819050919050565b6100c0816100ad565b81146100cb57600080fd5b50565b6000813590506100dd816100b7565b92915050565b600080fd5b600080fd5b600080fd5b60008083601f840112610108576101076100e3565b5b8235905067ffffffffffffffff811115610125576101246100e8565b5b602083019150836001820283011115610141576101406100ed565b5b9250929050565b600080600060408486031215610161576101606100a3565b5b600061016f868287016100ce565b935050602084013567ffffffffffffffff8111156101905761018f6100a8565b5b61019c868287016100f2565b92509250509250925092565b6101b1816100ad565b82525050565b600082825260208201905092915050565b82818337600083830152505050565b6000601f19601f8301169050919050565b60006101f483856101b7565b93506102018385846101c8565b61020a836101d7565b840190509392505050565b600060408201905061022a60008301866101a8565b818103602083015261023d8184866101e8565b905094935050505056fea26469706673582212202417516ca434a80e5a74f2b5a5e88d1ee6a341628969d455e078c393a1f75c1e64736f6c63430008140033";

type MockEmitterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockEmitterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockEmitter__factory extends ContractFactory {
  constructor(...args: MockEmitterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockEmitter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockEmitter__factory {
    return super.connect(runner) as MockEmitter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockEmitterInterface {
    return new Interface(_abi) as MockEmitterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MockEmitter {
    return new Contract(address, _abi, runner) as unknown as MockEmitter;
  }
}
