/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MockEmitterInterface extends Interface {
  getFunction(nameOrSignature: "emitSample"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Emitted"): EventFragment;

  encodeFunctionData(
    functionFragment: "emitSample",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "emitSample", data: BytesLike): Result;
}

export namespace EmittedEvent {
  export type InputTuple = [
    from: AddressLike,
    amount: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [from: string, amount: bigint, data: string];
  export interface OutputObject {
    from: string;
    amount: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockEmitter extends BaseContract {
  connect(runner?: ContractRunner | null): MockEmitter;
  waitForDeployment(): Promise<this>;

  interface: MockEmitterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  emitSample: TypedContractMethod<
    [amount: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "emitSample"
  ): TypedContractMethod<
    [amount: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Emitted"
  ): TypedContractEvent<
    EmittedEvent.InputTuple,
    EmittedEvent.OutputTuple,
    EmittedEvent.OutputObject
  >;

  filters: {
    "Emitted(address,uint256,bytes)": TypedContractEvent<
      EmittedEvent.InputTuple,
      EmittedEvent.OutputTuple,
      EmittedEvent.OutputObject
    >;
    Emitted: TypedContractEvent<
      EmittedEvent.InputTuple,
      EmittedEvent.OutputTuple,
      EmittedEvent.OutputObject
    >;
  };
}
